version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: "elasticsearch770"
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - cluster.name=tommy-es
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    privileged: true
    volumes:
      - /Users/huxiao/Downloads/temp770/data:/usr/share/elasticsearch/data
      - /Users/huxiao/Downloads/temp770/logs:/usr/share/elasticsearch/logs

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: kibana770
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601